// Dump every system-level prompt to a single human-readable markdown file at
// `docs/PROMPTS.md`.
//
// Source: each prompt's CURRENT published version in the local SQLite DB.
// `getPublishedPrompt()` auto-seeds the DB from `lib/prompt-store/seed.ts`
// BUILTINS on first call, so on a fresh checkout the dump matches the seed.
// After running `npm run apply-revised-prompts` the dump matches the revised
// content. This way PROMPTS.md tracks what the runtime actually uses.
//
// Run: `npm run dump-prompts`

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { listBuiltinKeys, getBuiltinBody } from "../lib/prompt-store/seed";
import { getPublishedPrompt } from "../lib/prompt-store";
import type { PromptBody } from "../lib/prompt-store/render";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "docs", "PROMPTS.md");

function fence(lang: string, body: string): string {
  // Pick a fence longer than any backtick run inside the body so we never
  // accidentally close the block early.
  const longest = Math.max(2, ...[...body.matchAll(/`+/g)].map((m) => m[0].length));
  const ticks = "`".repeat(longest + 1);
  return `${ticks}${lang}\n${body}\n${ticks}`;
}

function bodyAndVersion(key: string): { body: PromptBody | null; version: number | null; createdBy: string | null } {
  const stored = getPublishedPrompt(key, "system");
  if (stored) return { body: stored.body, version: stored.version, createdBy: stored.created_by };
  // Fallback for fresh DB without the key (shouldn't happen because
  // getPublishedPrompt auto-seeds, but be defensive).
  return { body: getBuiltinBody(key), version: null, createdBy: "seed (fallback)" };
}

function sectionFor(key: string): string {
  const { body, version, createdBy } = bodyAndVersion(key);
  if (!body) return `## ${key}\n\n_(missing)_\n`;
  const userMessage = body.messages?.[0]?.content ?? "";
  const meta = [
    `- **published version**: ${version !== null ? `v${version}` : "n/a"}${createdBy ? ` (created_by=\`${createdBy}\`)` : ""}`,
    `- **model**: \`${body.model ?? "(default)"}\``,
    `- **temperature**: \`${body.temperature ?? "(default)"}\``,
    `- **max_tokens**: \`${body.max_tokens ?? "(default)"}\``,
  ].join("\n");
  return [
    `## \`${key}\``,
    "",
    meta,
    "",
    "### System Prompt",
    "",
    fence("text", body.system ?? ""),
    "",
    "### User Message Template",
    "",
    fence("text", userMessage),
    "",
    "---",
    "",
  ].join("\n");
}

function main() {
  const keys = listBuiltinKeys();
  const now = new Date().toISOString().slice(0, 19).replace("T", " ");
  const header = [
    "# UMU Learning Library · System Prompts",
    "",
    `_Auto-dumped from the live DB's currently-published versions at ${now} UTC._`,
    "",
    "Do not edit this file by hand. It is rewritten by `npm run dump-prompts`,",
    "which reads each prompt's current published version from the SQLite DB.",
    "On a fresh checkout the DB auto-seeds from `lib/prompt-store/seed.ts`;",
    "after `npm run apply-revised-prompts` the dump reflects the revised content.",
    "",
    "## Index",
    "",
    ...keys.map(({ key, note }) => `- [\`${key}\`](#${anchor(key)}) — ${note}`),
    "",
    "---",
    "",
  ].join("\n");

  const sections = keys.map(({ key }) => sectionFor(key)).join("");

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, header + sections, "utf8");
  console.log(`Wrote ${keys.length} prompts → ${path.relative(ROOT, OUT)}`);
}

function anchor(key: string): string {
  // GitHub-flavoured markdown anchor for a `code-wrapped` heading: lowercase,
  // dots/underscores preserved as-is per GH rules.
  return key.toLowerCase();
}

main();
